// DHT sensor library - Version: Latest 

// LiquidCrystal - Version: Latest 
#include "thingProperties.h"
#include "LiquidCrystal.h"
#include "DHT.h"

/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/735893d5-947d-4b2f-9365-f117052a32f9 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float cO2_level;
  CloudTemperatureSensor temperatures;
  CloudRelativeHumidity humidity_level;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#define DHTPIN 27 // Sets the pin for the humidity sensor to 27
#define DHTTYPE DHT11 // Sets the sensor type to the Humidity sensor
DHT dht(DHTPIN, DHTTYPE);
LiquidCrystal lcd(12, 20, 26, 25, 33, 32);


void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  
  lcd.begin(16, 2); // Set up LCD for 16 columns and 2 rows
  lcd.setCursor(0, 0); // Set cursor to column 0, line 0
  lcd.print("Temp: "); // LCD top row print  | 6 Characters
  lcd.setCursor(0, 1); // Set cursor to column 0, line 1
  lcd.print("Humidity: "); // LCD bottom row print  | 10 Characters
}

void loop() 
{
  ArduinoCloud.update();
  // Your code here 
  
  delay(1000); // Wait for 1 second till switch
  
  float humidity = dht.readHumidity(); // Read the Humidity data
  float temperature = dht.readTemperature(); // Read the Temperature data

  lcd.setCursor(6, 0); // Set cursor to column 6, line 1 
  lcd.print(temperature); // LCD top row print temp value
  lcd.print("C"); // LCD top row print Celcius
  lcd.setCursor(10, 1); // Set cursor to column 0, line 1
  lcd.print(humidity); // LCD bottom row print humidity value
  lcd.print("%"); // LCD top row print Celcius

  delay(1000); // Wait for 1 second till switch
}
