/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/b92c4031-d936-437e-a1ac-56735ed8848a 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool relays;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

#define Relay_1 19 // Pin 19 for Relay 1
#define Relay_2 21 // Pin 21 for Reelay 2
#define Wifi_switch 27 // Pin 27 for the Wifi Switch activation
#define Relay_switch 26 // Pin 26 for the Relay switch activation
#define Wifi_LED 33 // Pin 33 for LED notification

void setup() 
{
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  
  pinMode(Relay_2, OUTPUT); // Set up both Relay pins as an output
  pinMode(Relay_2, OUTPUT);
  pinMode(Wifi_switch, INPUT);
  pinMode(Relay_switch, INPUT);
  pinMode(Wifi_LED, OUTPUT);
  
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}







/*
  Since Relays1N2 is READ_WRITE variable, onRelays1N2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onRelays1N2Change() 
{
  // Add your code here to act upon Relays1N2 change
  
}

/*
  Since RGBLeds is READ_WRITE variable, onRGBLedsChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onRGBLedsChange()  {
  // Add your code here to act upon RGBLeds change
}

/*
  Since Relays is READ_WRITE variable, onRelaysChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onRelaysChange()  
{
  // Add your code here to act upon Relays change
  if(relays)
  {
    digitalWrite(Relay_1, HIGH); // Activate Relay1
    digitalWrite(Relay_2, HIGH); // Activate Relay2
    delay(1000);
  }
  else
  {
    digitalWrite(Relay_1, LOW); // Deactivate Relay1
    digitalWrite(Relay_2, LOW); // Deactivate Relay2
    delay(1000);
  }
    
}



